wandb_version: 1

batch_size:
  value: 2
d_ff:
  value: 256
d_model:
  value: 16
dropout:
  value: 0.4
e_layers:
  value: 3
fc_dropout:
  value: 0.3
head_dropout:
  value: 0.2
learning_rate:
  value: 0.0005
n_heads:
  value: 16
