wandb_version: 1

batch_size:
  value: 1
d_ff:
  value: 128
d_model:
  value: 16
dropout:
  value: 0.2
e_layers:
  value: 3
fc_dropout:
  value: 0.3
head_dropout:
  value: 0.2
learning_rate:
  value: 0.0005
n_heads:
  value: 4
