wandb_version: 1

batch_size:
  value: 4
d_ff:
  value: 512
d_model:
  value: 32
dropout:
  value: 0.5
e_layers:
  value: 1
fc_dropout:
  value: 0.5
head_dropout:
  value: 0.2
learning_rate:
  value: 5.0e-05
n_heads:
  value: 1
