wandb_version: 1

batch_size:
  value: 2
d_ff:
  value: 32
d_model:
  value: 32
dropout:
  value: 0.2
e_layers:
  value: 2
fc_dropout:
  value: 0.4
head_dropout:
  value: 0.1
learning_rate:
  value: 0.0005
n_heads:
  value: 16
