wandb_version: 1

batch_size:
  value: 2
d_ff:
  value: 512
d_model:
  value: 16
dropout:
  value: 0.3
e_layers:
  value: 3
fc_dropout:
  value: 0.4
head_dropout:
  value: 0.2
learning_rate:
  value: 0.001
n_heads:
  value: 2
