program: run_Exp.py 
method: bayes   #grid, random, bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
     values: [0.001, 0.0005, 0.0001, 0.00005]
  batch_size:
    values: [1, 2, 4, 8]
  d_model:
    values: [16, 32, 64, 128, 256]      
  n_heads:
    values: [1, 2, 4, 8, 16]          
  e_layers:
    values: [1, 2, 3]           
  d_ff:
    values: [32, 64, 128, 256, 512]    
  dropout:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]                 
  fc_dropout:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]                  
  head_dropout:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]                 
