wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.19.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1751415066
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.9.19
      5: 0.19.8
      8:
      - 3
      - 5
      13: windows-amd64
random_seed:
  desc: null
  value: 1
is_training:
  desc: null
  value: 1
model_id:
  desc: null
  value: test
model:
  desc: null
  value: CausalPD
data:
  desc: null
  value: train
root_path:
  desc: null
  value: ./data/Shanghai/
data_path:
  desc: null
  value: pavement_distress.npy
ext_path:
  desc: null
  value: ext.csv
meta_dim:
  desc: null
  value: 0
features:
  desc: null
  value: M
target:
  desc: null
  value: OT
freq:
  desc: null
  value: d
checkpoints:
  desc: null
  value: ./checkpoints/
seq_len:
  desc: null
  value: 28
label_len:
  desc: null
  value: 14
pred_len:
  desc: null
  value: 7
fc_dropout:
  desc: null
  value: 0.5
head_dropout:
  desc: null
  value: 0.1
patch_len:
  desc: null
  value: 16
stride:
  desc: null
  value: 4
padding_patch:
  desc: null
  value: end
revin:
  desc: null
  value: 1
affine:
  desc: null
  value: 0
subtract_last:
  desc: null
  value: 0
individual:
  desc: null
  value: 0
enc_in:
  desc: null
  value: 7
d_model:
  desc: null
  value: 16
n_heads:
  desc: null
  value: 8
e_layers:
  desc: null
  value: 3
d_layers:
  desc: null
  value: 1
d_ff:
  desc: null
  value: 512
factor:
  desc: null
  value: 1
distil:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.2
embed:
  desc: null
  value: timeF
do_predict:
  desc: null
  value: false
use_intervention:
  desc: null
  value: 1
intervention_epochs:
  desc: null
  value: 50
attention_threshold:
  desc: null
  value: 0.5
entropy_weight:
  desc: null
  value: 0.05
consistency_weight:
  desc: null
  value: 0.1
K:
  desc: null
  value: 4
intervention_prob:
  desc: null
  value: 0.7
intervention_lr_scale:
  desc: null
  value: 0.1
intervention_lr_decay:
  desc: null
  value: 0.95
num_workers:
  desc: null
  value: 0
itr:
  desc: null
  value: 1
train_epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 2
patience:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0005
des:
  desc: null
  value: test
loss:
  desc: null
  value: mse
lradj:
  desc: null
  value: type3
pct_start:
  desc: null
  value: 0.3
use_amp:
  desc: null
  value: true
use_gpu:
  desc: null
  value: true
gpu:
  desc: null
  value: 0
use_multi_gpu:
  desc: null
  value: false
devices:
  desc: null
  value: 0,1,2,3
test_flop:
  desc: null
  value: false
