wandb_version: 1

batch_size:
  value: 32
d_ff:
  value: 64
d_model:
  value: 128
dropout:
  value: 0.1
e_layers:
  value: 2
fc_dropout:
  value: 0.2
head_dropout:
  value: 0.3
learning_rate:
  value: 0.0005
n_heads:
  value: 1
