wandb_version: 1

batch_size:
  value: 16
d_ff:
  value: 512
d_model:
  value: 256
dropout:
  value: 0.2
e_layers:
  value: 3
fc_dropout:
  value: 0.3
head_dropout:
  value: 0.2
learning_rate:
  value: 5.0e-05
n_heads:
  value: 2
