wandb_version: 1

batch_size:
  value: 8
d_ff:
  value: 32
d_model:
  value: 128
dropout:
  value: 0.2
e_layers:
  value: 2
fc_dropout:
  value: 0.2
head_dropout:
  value: 0.2
learning_rate:
  value: 5.0e-05
n_heads:
  value: 16
