wandb_version: 1

batch_size:
  value: 32
d_ff:
  value: 256
d_model:
  value: 32
dropout:
  value: 0.4
e_layers:
  value: 1
fc_dropout:
  value: 0.1
head_dropout:
  value: 0.4
learning_rate:
  value: 5.0e-05
n_heads:
  value: 16
