wandb_version: 1

batch_size:
  value: 32
d_ff:
  value: 256
d_model:
  value: 128
dropout:
  value: 0.5
e_layers:
  value: 2
fc_dropout:
  value: 0.2
head_dropout:
  value: 0.4
learning_rate:
  value: 0.001
n_heads:
  value: 8
