wandb_version: 1

batch_size:
  value: 32
d_ff:
  value: 512
d_model:
  value: 256
dropout:
  value: 0.4
e_layers:
  value: 1
fc_dropout:
  value: 0.5
head_dropout:
  value: 0.4
learning_rate:
  value: 0.0005
n_heads:
  value: 8
